repos:
-   repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
    -   id: fmt
    -   id: cargo-check
    -   id: clippy
-   repo: local
    hooks:
    -   id: cargo-test
        name: cargo-test
        entry: cargo test
        language: system
        types: [rust]
        pass_filenames: false
