[package]
name = "tmgr"
version = "1.0.0"
edition = "2021"
authors = ["Charlie Karafotias <cnkara2023@gmail.com>"]
repository = "https://github.com/charliekarafotias/tmgr"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
serde = { version = "1.0.209", features = ["derive"] }
surrealdb = { version = "1.5.4", features = ["kv-mem", "kv-rocksdb"] }
tokio = { version = "1.39.3", features = ["macros", "rt-multi-thread"] }
chrono = "0.4.38"
