[package]
name = "tmgr"
version = "2.2.4"
edition = "2021"
authors = ["Charlie Karafotias <cnkara2023@gmail.com>"]
repository = "https://github.com/charliekarafotias/tmgr"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
serde = { version = "1.0.216", features = ["derive"] }
surrealdb = { version = "2.1.3", features = ["kv-mem", "kv-surrealkv"] }
tokio = { version = "1.42.0", features = ["macros", "rt-multi-thread"] }
reqwest = { version = "0.12.9", features = ["json"] }
semver = "1.0.24"
directories = "5.0.1"
colored = "2.2.0"
comfy-table = "7.1.3"


[dev-dependencies]
chrono = "0.4.39"
tempfile = "3.14.0"
