[package]
name = "tmgr"
version = "0.1.0"
edition = "2021"
authors = ["Charlie Karafotias <cnkara2023@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
sqlite = "0.32.0"
