[package]
name = "tmgr"
version = "2.2.3"
edition = "2021"
authors = ["Charlie Karafotias <cnkara2023@gmail.com>"]
repository = "https://github.com/charliekarafotias/tmgr"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
serde = { version = "1.0.215", features = ["derive"] }
surrealdb = { version = "2.1.2", features = ["kv-mem", "kv-surrealkv"] }
tokio = { version = "1.41.1", features = ["macros", "rt-multi-thread"] }
serde_json = "1.0.133"
reqwest = { version = "0.12.9", features = ["json"] }
semver = "1.0.23"
directories = "5.0.1"
colored = "2.1.0"
comfy-table = "7.1.3"


[dev-dependencies]
chrono = "0.4.38"
tempfile = "3.14.0"
